on:
  - push
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '* 72 * * *'

jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
          - args: [--global, gulp, prettier, typescript]

    - run: pnpm build
    - run: node dist/index.js
